/**
 * The shader environment contract, version 1 — the vocabulary an effect record
 * may assume. This module is the single home of the grammar: the publish
 * script validates against it before a record leaves the author's machine,
 * and the app validates against it when a record arrives from the network.
 * It imports nothing from the rest of the app so it can one day be extracted
 * as its own package with a `git mv`.
 *
 * What env 1 guarantees a body may reference:
 *   - `imageTexture` (sampler2D): the pass input — the photo, or the prior
 *     pass's output in a chain. Host-provided; never declared as a param.
 *   - `vUv` (vec2 varying): normalized texture coordinates.
 *   - `time` (float): seconds. Referencing it makes the effect animated,
 *     unless `animatedBy` names a range param that gates the motion (0 ⇒ still).
 *   - `resolution` (vec2): render size in pixels.
 *   - `prevFrame` (sampler2D): the previous rendered frame. Referencing it
 *     makes the effect a feedback effect — always animated, ungateable.
 *   - `opacity` (float): host-injected layer strength; every effect's output
 *     is mixed with its input by this value. Not declarable.
 *
 * What a body must be: GLSL ES 1.00 fragment code containing `void main()`
 * and writing `gl_FragColor`. Uniform declarations are generated by the host
 * from the param list, so the body must not declare its own.
 */

export const EFFECT_COLLECTION = 'com.luminframe.effect'

export const ENV_VERSION = 1

/** Host-provided uniform/varying names an effect may read but never declare as params. */
export const RESERVED_UNIFORMS = [
  'imageTexture',
  'vUv',
  'time',
  'resolution',
  'prevFrame',
  'opacity',
] as const

/** Internal identifiers the host's body-wrapping generates; a body containing them would collide. */
export const RESERVED_TOKENS = ['lfFragColor', 'lfEffectMain'] as const

export const MAX_NAME_LENGTH = 64
export const MAX_BODY_LENGTH = 20000
export const MAX_PARAMS_JSON_LENGTH = 10000

/** Param names must be plain GLSL identifiers. */
export const PARAM_NAME_PATTERN = /^[a-zA-Z_][a-zA-Z0-9_]*$/

/**
 * An effect's slug becomes its record key (rkey), so its shape is grammar:
 * lowercase letters, digits, hyphens, starting alphanumeric. Enforced here by
 * the in-app creator and by scripts/publish-effect.ts. Look slugs follow the
 * same rule (a slug may repeat across the two collections without conflict).
 */
export const EFFECT_SLUG_PATTERN = /^[a-z0-9][a-z0-9-]*$/

/*
 * The recipe record — a "Look": a named chain of effect steps, optionally
 * with macro knobs. Composition as data: a Look is rendered as N passes and
 * can always be reopened into its chain, never fused into one shader.
 */

export const RECIPE_COLLECTION = 'com.luminframe.recipe'

/** Matches the image record's recipe maxLength — one saved edit is one Look. */
export const MAX_STEPS = 64

export const MAX_MACROS = 8

/** A step key: a builtin effect name or an at:// effect URI (lexicon caps it). */
export const MAX_STEP_KEY_LENGTH = 128

/** Builtin effect keys are plain identifiers (blur, crossHatch, …). */
export const STEP_KEY_PATTERN = /^[a-zA-Z_][a-zA-Z0-9_]*$/
