/**
 * The shader environment contract, version 1 — the vocabulary an effect record
 * may assume. This module is the single home of the grammar: the publish
 * script validates against it before a record leaves the author's machine,
 * and the app validates against it when a record arrives from the network.
 * It imports nothing from the rest of the app so it can one day be extracted
 * as its own package with a `git mv`.
 *
 * What env 1 guarantees a body may reference:
 *   - `imageTexture` (sampler2D): the pass input — the photo, or the prior
 *     pass's output in a chain. Host-provided; never declared as a param.
 *   - `vUv` (vec2 varying): normalized texture coordinates.
 *   - `time` (float): seconds. Referencing it makes the effect animated,
 *     unless `animatedBy` names a range param that gates the motion (0 ⇒ still).
 *   - `resolution` (vec2): the source image's pixel dimensions — NOT the size
 *     of the buffer being drawn into, which follows the on-screen canvas in the
 *     editor and the image in export. Sizing off the image is what makes the
 *     live view predict the export for grain-, dot- and cell-sized effects.
 *     A body should derive position from `vUv` and use `resolution` only for
 *     pixel scale or aspect ratio; `gl_FragCoord` is in buffer space and so
 *     does not agree with `resolution` on any surface but export.
 *   - `prevFrame` (sampler2D): the previous rendered frame. Referencing it
 *     makes the effect a feedback effect — always animated, ungateable.
 *   - `opacity` (float): host-injected layer strength; every effect's output
 *     is mixed with its input by this value. Not declarable.
 *
 * What a body must be: GLSL ES 1.00 fragment code containing `void main()`
 * and writing `gl_FragColor`. Uniform declarations are generated by the host
 * from the param list, so the body must not declare its own.
 *
 * Env 2 adds three capabilities to the param vocabulary (the body rules are
 * unchanged):
 *   - `image` params: extra sampler2D slots the user fills with pictures.
 *     An unfilled slot is a black texture BY CONTRACT — effects should
 *     degrade gracefully against black rather than assume a picture.
 *   - `text` params: typed text the host rasterizes to a sampler2D whose
 *     alpha channel carries the glyphs (white on transparent).
 *   - vec2 bounds (`min`/`max`/`step`, optionally `labels`): track limits
 *     for pairs that are normalized points rather than pixel counts.
 * A record must declare the smallest env its params require (see
 * `minimalEnvFor`) so env-1 clients keep reading everything they can speak.
 */

export const EFFECT_COLLECTION = 'com.luminframe.effect'

export const ENV_VERSION = 2

/**
 * Ceiling on declared texture-valued params (image + text combined). From
 * hardware, not taste: WebGL1 guarantees only 8 fragment texture units and
 * the host spends up to 2 (`imageTexture`, plus `prevFrame` for feedback
 * effects) — 1 + 1 + 4 = 6 leaves headroom on the worst guaranteed GPU, so a
 * record that compiles on the author's machine can't fail on a phone.
 */
export const MAX_TEXTURE_PARAMS = 4

/** Host-provided uniform/varying names an effect may read but never declare as params. */
export const RESERVED_UNIFORMS = [
  'imageTexture',
  'vUv',
  'time',
  'resolution',
  'prevFrame',
  'opacity',
] as const

/** Internal identifiers the host's body-wrapping generates; a body containing them would collide. */
export const RESERVED_TOKENS = ['lfFragColor', 'lfEffectMain'] as const

export const MAX_NAME_LENGTH = 64
export const MAX_BODY_LENGTH = 20000
export const MAX_PARAMS_JSON_LENGTH = 10000

/** Param names must be plain GLSL identifiers. */
export const PARAM_NAME_PATTERN = /^[a-zA-Z_][a-zA-Z0-9_]*$/

/**
 * An effect's slug becomes its record key (rkey), so its shape is grammar:
 * lowercase letters, digits, hyphens, starting alphanumeric. Enforced here by
 * the in-app creator and by scripts/publish-effect.ts.
 */
export const EFFECT_SLUG_PATTERN = /^[a-z0-9][a-z0-9-]*$/
